---
- hosts: all
  become: true

  tasks:
  - name: build docker image using war file
    command: docker build . -t new_dockerfile
    args:
      chdir: /opt/docker   
  - name: Create container from image
    command: docker run -d --name new_conatiner -p 8080:8080 new_dockerfile   
